# Generated by Django 4.2.3 on 2023-07-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_moment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='kind',
            field=models.CharField(choices=[('Python技術', 'Python技術'), ('資料庫技術', '資料庫技術'), ('經濟學', '經濟學'), ('文體資訊', '文體資訊'), ('個人心情', '個人心情'), ('其他', '其他')], default=('Python技術', 'Python技術'), max_length=20),
        ),
    ]
